version: "3"
services:
  bot-api:
    container_name: ${APPLICATION}-api
    build: ${DOCKERFILE_DIR}
    environment:
      - CONTAINER_DIR = "${CONTAINER_DIR}"
    ports:
      - "${HOST_PORT}:5000"
    volumes:
      - ${HOST_WORKING_DIR}:${CONTAINER_DIR}
    